#!/usr/bin/bash

ABS="$( realpath ${BASH_SOURCE[0]})"
DIR="$( dirname $ABS)"

export SCIPION_ROOT=$DIR
export SCIPION_HOME=$SCIPION_ROOT
export SCIPION_DOMAIN=pwem
export SCIPION_TESTS_CMD='scipion test'
export SCIPION_SW=$SCIPION_ROOT/conda
export SCIPION_EM=$SCIPION_ROOT/EM
export SCIPION_CONFIG=$SCIPION_HOME/config/scipion.conf

# Needed by some plugins
export EM_ROOT=$SCIPION_EM
export SCIPION_PLUGINS=$SCIPION_ROOT/source/plugins
# Activate the environment
export PATH=$SCIPION_SW/bin:$PATH
#export LD_LIBRARY_PATH=$SCIPION_SW/lib:$LD_LIBRARY_PATH

# Setup Xmipp
export XMIPP_HOME=$SCIPION_HOME/source/xmipp-bundle/build
export PATH=$XMIPP_HOME/bin:$PATH
export LD_LIBRARY_PATH=$XMIPP_HOME/lib:$XMIPP_HOME/bindings/python:$LD_LIBRARY_PATH
export PYTHONPATH=$XMIPP_HOME/bindings/python:$XMIPP_HOME/pylib:$PYTHONPATH

# EMhub Variables
export EMHUB_INSTANCE=~/.emhub/instances/test
export FLASK_APP=emhub
export FLASK_ENV=development

# EMhub client variables
export EMHUB_SERVER_URL=https://127.0.0.1:5000
export EMHUB_USER=admin
export EMHUB_PASSWORD=admin

alias scipion='scipion --config $SCIPION_CONFIG'


